# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-with-tests-arg:
    runs-on: ubuntu-latest
    steps:
    - name: MOxUnit Action
      uses: joergbrech/moxunit-action@v1.1
      with:
        tests: AMC-ASF-Tools/tests
        src: AMC-ASF-Tools/tbx/AMC-ASF-Tools
